Create a Spring Boot project
vlykhvar/MyBankService pull request #1
Opened 2021-02-27 22:13 UTC by vlykhvar

- Create a Spring Boot project

- Added checkstyle plugin and configured Travis. 

- Added User and Role entities, the repository and service levels for them.

2021-02-28 19:02 UTC, YuraBondarenko approved these changes

2021-02-28 19:02 UTC, YuraBondarenko commented on src/main/java/com/example/bankoflykhvar/config/AppConfig.java
> +}
this class isn't necessary with spring boot

2021-02-28 19:28 UTC, vlykhvar commented on src/main/java/com/example/bankoflykhvar/config/AppConfig.java
> +}
agree

2021-03-01 09:16 UTC, KseniiaMakarova requested changes

2021-03-01 09:16 UTC, KseniiaMakarova commented on src/main/java/com/example/bankoflykhvar/model/User.java
> +import com.sun.istack.NotNull;
let's not use this annotation

2021-03-01 09:16 UTC, KseniiaMakarova commented on src/main/java/com/example/bankoflykhvar/model/User.java
> +    private LocalDate dateOfBirth;
see checklist - `If your column name contains of several words (phoneNumber) - be sure that they are correctly mapped to DB columns (phone_number).`

2021-03-01 09:16 UTC, KseniiaMakarova commented on src/main/java/com/example/bankoflykhvar/model/User.java
> +    private String phoneNumber;
same

2021-03-01 09:16 UTC, KseniiaMakarova commented on src/main/java/com/example/bankoflykhvar/model/User.java
> +    @OneToMany
let's reconsider this relationship

2021-03-01 09:16 UTC, KseniiaMakarova commented on src/main/java/com/example/bankoflykhvar/repository/RoleRepository.java
> +    Optional<Role> getByName(String name);
```suggestion
    Optional<Role> getByRoleName(Role.RoleName name);
```
Spring Data JPA is capable of automatically build the query in many cases based on the method name and parameters)

2021-03-01 09:16 UTC, KseniiaMakarova commented on src/main/java/com/example/bankoflykhvar/service/UserService.java
> +    User update(User user);
see checklist

2021-03-01 09:16 UTC, KseniiaMakarova commented on src/main/java/com/example/bankoflykhvar/service/impl/UserServiceImpl.java
> +@Component
why Component?

2021-03-01 09:16 UTC, KseniiaMakarova commented on src/main/resources/application.properties
> +spring.h2.console.enabled=true
```suggestion
spring.h2.console.enabled=true
spring.h2.console.path=/h2
```
by which path is the console available at the moment?

2021-03-01 11:16 UTC, KseniiaMakarova requested changes

2021-03-01 11:16 UTC, KseniiaMakarova commented on src/main/java/com/example/bankoflykhvar/repository/RoleRepository.java
> +    Optional<Role> getByRoleName(String roleName);
does it work with parameter of type String?

2021-03-01 11:16 UTC, KseniiaMakarova commented on src/main/java/com/example/bankoflykhvar/service/impl/UserServiceImpl.java
>      public User update(User user) {
let's remove this method?

2021-03-01 13:13 UTC, KseniiaMakarova requested changes

2021-03-01 13:13 UTC, KseniiaMakarova commented on src/main/java/com/example/bankoflykhvar/service/impl/UserServiceImpl.java
> +        if (newUser == null) {
can you get null here?...

2021-03-01 13:13 UTC, KseniiaMakarova commented on src/main/java/com/example/bankoflykhvar/service/impl/UserServiceImpl.java
>      public User update(User user) {
let's add this method on the interface level as well, if you decided so

2021-03-01 15:15 UTC, KseniiaMakarova approved these changes

2021-03-01 15:20 UTC, merged